// <auto-generated />
using historianproductionservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace historianproductionservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180824133242_Genealogia")]
    partial class Genealogia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Aco", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EndRollid");

                    b.Property<string>("batch");

                    b.Property<string>("code");

                    b.Property<long>("endDate");

                    b.Property<string>("quantity");

                    b.Property<long>("startDate");

                    b.HasKey("id");

                    b.HasIndex("EndRollid");

                    b.ToTable("Aco");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Elemento", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Ligaid");

                    b.Property<string>("batch");

                    b.Property<long>("date");

                    b.Property<string>("product");

                    b.Property<string>("quantity");

                    b.HasKey("id");

                    b.HasIndex("Ligaid");

                    b.ToTable("Elemento");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.EndRoll", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Genealogyid");

                    b.Property<long>("endDate");

                    b.Property<long>("productionOrderId");

                    b.Property<string>("quantity");

                    b.Property<long?>("startDate");

                    b.HasKey("id");

                    b.HasIndex("Genealogyid");

                    b.ToTable("EndRoll");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Genealogy", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("endDate");

                    b.Property<long>("orderId");

                    b.Property<string>("productionOrderNumber");

                    b.Property<string>("recipeCode");

                    b.Property<string>("recipeid");

                    b.Property<long>("startDate");

                    b.HasKey("id");

                    b.ToTable("Genealogy");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Liga", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EndRollid");

                    b.Property<string>("batch");

                    b.Property<string>("code");

                    b.Property<long>("endDate");

                    b.Property<long>("orderId");

                    b.Property<string>("orderNumber");

                    b.Property<string>("quantity");

                    b.Property<long>("startDate");

                    b.HasKey("id");

                    b.HasIndex("EndRollid");

                    b.ToTable("Liga");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Tool", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EndRollid");

                    b.Property<string>("group");

                    b.Property<string>("serialNumber");

                    b.Property<string>("toolId");

                    b.Property<string>("typeName");

                    b.Property<string>("vidaUtil");

                    b.HasKey("id");

                    b.HasIndex("EndRollid");

                    b.ToTable("Tool");
                });

            modelBuilder.Entity("historianproductionservice.Model.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("order");

                    b.Property<int>("productionOrderId");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("historianproductionservice.Model.ProductTraceability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Orderid");

                    b.Property<int?>("Orderid1");

                    b.Property<string>("batch");

                    b.Property<string>("code");

                    b.Property<long>("date");

                    b.Property<string>("product");

                    b.Property<int>("productId");

                    b.Property<string>("productType");

                    b.Property<double>("quantity");

                    b.Property<string>("unity");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.HasIndex("Orderid");

                    b.HasIndex("Orderid1");

                    b.ToTable("ProductTraceabilities");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Aco", b =>
                {
                    b.HasOne("historianproductionservice.Model.Genealogy.EndRoll")
                        .WithMany("inputRolls")
                        .HasForeignKey("EndRollid");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Elemento", b =>
                {
                    b.HasOne("historianproductionservice.Model.Genealogy.Liga")
                        .WithMany("productsInput")
                        .HasForeignKey("Ligaid");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.EndRoll", b =>
                {
                    b.HasOne("historianproductionservice.Model.Genealogy.Genealogy")
                        .WithMany("outputRolls")
                        .HasForeignKey("Genealogyid");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Liga", b =>
                {
                    b.HasOne("historianproductionservice.Model.Genealogy.EndRoll")
                        .WithMany("ligas")
                        .HasForeignKey("EndRollid");
                });

            modelBuilder.Entity("historianproductionservice.Model.Genealogy.Tool", b =>
                {
                    b.HasOne("historianproductionservice.Model.Genealogy.EndRoll")
                        .WithMany("tools")
                        .HasForeignKey("EndRollid");
                });

            modelBuilder.Entity("historianproductionservice.Model.ProductTraceability", b =>
                {
                    b.HasOne("historianproductionservice.Model.Order")
                        .WithMany("productsInput")
                        .HasForeignKey("Orderid");

                    b.HasOne("historianproductionservice.Model.Order")
                        .WithMany("productsOutput")
                        .HasForeignKey("Orderid1");
                });
#pragma warning restore 612, 618
        }
    }
}
